# Parameter for the control of the workflow of the analysis pipeline

job:
  dir: 'jobs/job_test'

preprocessing:
  patch_dimension: [128,128]
  #input_dir: "/lustrehome/garamire/share/agri2intesa/s1_to_s2/train/"
  input_dir: "/Users/garamire/Work/AgriIntesa/fromRoberto/share/agri2intesa/s1_to_s2/train"
  do_norm_params: false
  norm_params_file: "normalization_params.npz"
  #norm_params_path: "/lustrehome/garamire/share/agri2intesa/s1_to_s2/normalization_params.npz"
  precalc_norm_params_path: "/Users/garamire/Work/AgriIntesa/fromRoberto/share/agri2intesa/s1_to_s2/normalization_params.npz"
  sample_size: 6 # Use 0 to use all the scenes in the training input_dir


model:
  #name: "UNet"
  name: "SMP_UNet"
  parameters:
    encoder_name: "efficientnet-b0"
    encoder_weights: "imagenet"
    in_channels: 4
    classes: 9
training:
  model_output: "trained_model.pth" # Path to the output model file.
  data:
    train_dataset: "train_dataset_S2.h5"
    val_dataset: "val_dataset_S2.h5"
    batch_size: 128
    n_workers: 8
  n_epochs: 2
  patience: 1
  optimizer: 
    name: "Adam"
    parameters:
      lr: 1e-4 # Learning rate
  loss:
    name: "CombinedLoss"
    parameters:
      alpha: 1.0
      beta: 2
      gamma: 0.1
inference:
  #input_dir: "/Users/garamire/Work/AgriIntesa/fromRoberto/share/agri2intesa/s1_to_s2/test" 
  output_dir: "output_combined/"
  sample_size: 6 # Use 0 to use all the scenes in the testing input_dir
evaluation:
  scenes_to_plot: 2

target:
  band_type: true # True if the output are 9 bands of Sentinel2. 
  all_bands: ["b1","blue", "green", "red", "b5", "rededge", "b7", "nir","b8a","b9", "b10", "swir", "b12"]
  selected_bands: [1,2,3,4,5,6,7,10,11]  # The number of elements of this list should match the number of output classes

params:
  vegetation_indices: ["ndvi", "gndvi", "ndre", "reci", "msi", "ndwi", "evi", "savi", "arvi", "cig", "cire", "bsi", "ndsi", "mcari"]
