# Parameter for the control of the workflow of the analysis pipeline

preprocessing:
  patch_dimension: [128,128]
training:
  batch_size: 4
  n_workers: 4
  input_dataset_name: "data/train_dataset_S2.h5"
  output_dir: "data/output_combined/"
  model:
    name: "UNet"
    parameters:
      encoder_name: "efficientnet-b0"
      encoder_weights: "imagenet"
      in_channels: 4
      classes: 9
      path: "best_model.pth" # Path to the output model file.
  optimizer: 
    name: "Adam"
    parameters:
      lr: 1e-4 # Learning rate
  loss:
    name: "CombinedLoss"
    parameters:
      alpha: 1.0
      beta: 2
      gamma: 0.1
inference:
  input_dir: "data/inference/"





