# Parameter for the control of the workflow of the analysis pipeline

preprocessing:
  patch_dimension: [128,128]

data_loader:
  batch_size: 4
  n_workers: 0 

model:
  #name: "UNet"
  name: "SMP_UNet"
  parameters:
    encoder_name: "efficientnet-b0"
    encoder_weights: "imagenet"
    in_channels: 4
    classes: 9
training:
  train_dataset: "data/train_dataset_S2.h5"
  val_dataset: "data/val_dataset_S2.h5"
  output_dir: "data/output_combined/"
  output_path_model: "best_model.pth" # Path to the output model file.
  optimizer: 
    name: "Adam"
    parameters:
      lr: 1e-4 # Learning rate
  loss:
    name: "CombinedLoss"
    parameters:
      alpha: 1.0
      beta: 2
      gamma: 0.1
inference:
  input_dir: "data/inference/"





